#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*             linuxserver/couchpotato                *
*                                                    *
*  https://hub.docker.com/r/linuxserver/couchpotato  *
*                                                    *
* https://github.com/linuxserver/docker-couchpotato  *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
